name: Git Builds

on:
  schedule:
    # At minute 17 past hour 8 and 14 (UTC) on every day-of-week from Monday through Thursday
    # https://crontab.guru
    - cron: '17 08,14 * * 1-5'
  workflow_dispatch:

env:
  ProjectFile: "src/NexusMods.App/NexusMods.App.csproj"

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest , macos-latest ]
jobs:
  transformInputs:
    runs-on: ubuntu-latest
    outputs:
      ProjectFile: ${{ steps.setOutputs.outputs.projectFile }}

    steps:
      - name: Set Outputs
        id: setOutputs
        shell: pwsh
        run: scripts\build-win-x64.ps1
      - name: Build (macOS)
        if: runner.os == 'macOS'
        shell: sh
        run: ./scripts/build-macos.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          # example: "NexusMods.App-Windows-279a5092173a6f687f89dc3c6a2b7c5898e289f6"
          name: NexusMods.App-${{ runner.os }}-${{ github.sha }}
          path: ${{ github.workspace }}/bin
          if-no-files-found: error
          retention-days: 7
        run: |
          echo "projectFile=${{ env.ProjectFile }}" >> $env:GITHUB_OUTPUT

  build-linux:
    needs: [ transformInputs ]
    uses: ./.github/workflows/build-linux-pupnet.yaml
    with:
      AppVersion: "0.0.1"
      # this is a bit of a hack, you can't use environment variables here
      # https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
      ProjectFile: ${{ needs.transformInputs.outputs.ProjectFile }}
      RetentionDays: 3

  build-windows:
    needs: [ transformInputs ]
    uses: ./.github/workflows/build-windows-pupnet.yaml
    with:
      AppVersion: "0.0.1"
      # this is a bit of a hack, you can't use environment variables here
      # https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
      ProjectFile: ${{ needs.transformInputs.outputs.ProjectFile }}
      RetentionDays: 3
