name: Git Builds

on:
  schedule:
    # At minute 17 past hour 8 and 14 (UTC) on every day-of-week from Monday through Thursday
    # https://crontab.guru
    - cron: '17 08,14 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest , macos-latest ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Info
        run: dotnet --info

      - name: Build (Linux)
        if: runner.os == 'Linux'
        shell: sh
        run: ./scripts/build-linux-x64.sh

      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: scripts\build-win-x64.ps1
      - name: Build (macOS)
        if: runner.os == 'macOS'
        shell: sh
        run: ./scripts/build-macos.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          # example: "NexusMods.App-Windows-279a5092173a6f687f89dc3c6a2b7c5898e289f6"
          name: NexusMods.App-${{ runner.os }}-${{ github.sha }}
          path: ${{ github.workspace }}/bin
          if-no-files-found: error
          retention-days: 7
