name: Signing Test

on:
  schedule:
    # At 14:05 on Wednesday
    # https://crontab.guru
    - cron: '5 14 * * 3'
  workflow_dispatch:

env:
  ProjectFile: "src/NexusMods.App/NexusMods.App.csproj"

jobs:
  transformInputs:
    runs-on: ubuntu-latest
    outputs:
      ProjectFile: ${{ steps.setOutputs.outputs.projectFile }}

    steps:
      - name: Set Outputs
        id: setOutputs
        shell: pwsh
        run: |
          echo "projectFile=${{ env.ProjectFile }}" >> $env:GITHUB_OUTPUT

  build-windows:
    needs: [ transformInputs ]
    uses: ./.github/workflows/build-windows-pupnet.yaml
    with:
      AppVersion: "0.0.1"
      # this is a bit of a hack, you can't use environment variables here
      # https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
      ProjectFile: ${{ needs.transformInputs.outputs.ProjectFile }}
      RetentionDays: 1
      SignExecutable: true
      BuildArchive: false
      BuildInnoSetup: true
    secrets:
      ES_USERNAME: ${{ secrets.ES_USERNAME }}
      ES_PASSWORD: ${{ secrets.ES_PASSWORD }}
      ES_CREDENTIAL_ID: ${{ secrets.ES_CREDENTIAL_ID }}
      ES_TOTP_SECRET: ${{ secrets.ES_TOTP_SECRET }}
